name: Go Workflow

on:
  issues:
    types: [opened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: mkdir -p bin && go build -o bin/caller src/script/caller.go

    - name: Run
      run: ./bin/caller "${{ secrets.CLOUDFLARE_WORKER }}" "${{ github.event.issue.number }}" "${{ github.event.issue.title }}" "${{ github.event.issue.body }}"
